version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - USER_POOL_ID=$(aws cognito-idp list-user-pools --max-results 10 --output text --query "UserPools[0].Id" --region us-east-1)
      - CLIENT_ID=$(aws cognito-idp list-user-pool-clients --user-pool-id $USER_POOL_ID --output text --query "UserPoolClients[0].ClientId" --region us-east-1)
      # - SECRET_ID=$(aws cognito-idp describe-user-pool-client --user-pool-id $USER_POOL_ID --client-id $CLIENT_ID --output text --query "UserPoolClient.ClientSecret" --region us-east-1)
      - sed -i "s/INSERT_AWS_COGNITO_USER_POOL_ID/$USER_POOL_ID/g" main.py
      - sed -i "s/INSERT_AWS_COGNITO_USER_POOL_CLIENT_ID/$CLIENT_ID/g" main.py
      # - sed -i "s/INSERT_AWS_COGNITO_USER_POOL_CLIENT_SECRET/$SECRET_ID/g" main.py
      - cat main.py
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/myecr:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/myecr:latest
